version: '3.8'

services:
  php:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: pt-php
    volumes:
      - ../NexusPHP:/var/www/NexusPHP
      - ../log/php:/tmp
    command: /bin/sh -c "composer install && php-fpm -F"
    networks:
      - nexusphp-network

  nginx:
    image: nginx:alpine
    container_name: pt-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../NexusPHP:/var/www/NexusPHP
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ../log/nginx:/var/log/nginx
    command: /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      - php
    networks:
      - nexusphp-network
    
  mysql:
    image: mysql:8.0.39-debian
    container_name: pt-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql:/var/lib/mysql 
      - ../mysql:/etc/mysql/conf.d 
      - ../log/mysql:/var/log/mysql
    depends_on:
      - php  
    networks:
      - nexusphp-network

  redis:
    image: redis:alpine
    container_name: pt-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data 
      - ../redis:/usr/local/etc/redis 
      - ../log/redis:/var/log/redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    depends_on:
      - php 
    networks:
      - nexusphp-network

networks:
  nexusphp-network:
    driver: bridge